# Generated by Django 2.2.24 on 2021-10-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comand',
            new_name='Comands',
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='Messages',
        ),
        migrations.RenameModel(
            old_name='State',
            new_name='Status',
        ),
    ]
